### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [robertsapunarich/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by robertsapunarich** [comment]
Perfect! It looks a lot better. Thanks Ken.

**Comment by kenmazaika** [comment]
Happy to help, Robert! Your code looks great now!
